<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aditya Ranganath">

<title>R Foundations: Basics of Functional Programming</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="session2_files/libs/clipboard/clipboard.min.js"></script>
<script src="session2_files/libs/quarto-html/quarto.js"></script>
<script src="session2_files/libs/quarto-html/popper.min.js"></script>
<script src="session2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="session2_files/libs/quarto-html/anchor.min.js"></script>
<link href="session2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="session2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="session2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="session2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="session2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#built-in-functions" id="toc-built-in-functions" class="nav-link" data-scroll-target="#built-in-functions"><span class="header-section-number">2</span> Built-In Functions</a></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages"><span class="header-section-number">3</span> Packages</a>
  <ul class="collapse">
  <li><a href="#installing-packages" id="toc-installing-packages" class="nav-link" data-scroll-target="#installing-packages"><span class="header-section-number">3.1</span> Installing Packages</a></li>
  <li><a href="#loading-libraries" id="toc-loading-libraries" class="nav-link" data-scroll-target="#loading-libraries"><span class="header-section-number">3.2</span> Loading Libraries</a></li>
  </ul></li>
  <li><a href="#writing-custom-functions" id="toc-writing-custom-functions" class="nav-link" data-scroll-target="#writing-custom-functions"><span class="header-section-number">4</span> Writing Custom Functions</a>
  <ul class="collapse">
  <li><a href="#writing-one-input-functions" id="toc-writing-one-input-functions" class="nav-link" data-scroll-target="#writing-one-input-functions"><span class="header-section-number">4.1</span> Writing One-Input Functions</a></li>
  <li><a href="#writing-two-input-functions" id="toc-writing-two-input-functions" class="nav-link" data-scroll-target="#writing-two-input-functions"><span class="header-section-number">4.2</span> Writing Two-Input Functions</a></li>
  <li><a href="#multiple-input-gdp-calculation-function" id="toc-multiple-input-gdp-calculation-function" class="nav-link" data-scroll-target="#multiple-input-gdp-calculation-function"><span class="header-section-number">4.3</span> Multiple-Input GDP Calculation Function</a></li>
  <li><a href="#if-then-statements-in-functions" id="toc-if-then-statements-in-functions" class="nav-link" data-scroll-target="#if-then-statements-in-functions"><span class="header-section-number">4.4</span> if-then Statements in Functions</a></li>
  </ul></li>
  <li><a href="#iteration" id="toc-iteration" class="nav-link" data-scroll-target="#iteration"><span class="header-section-number">5</span> Iteration</a>
  <ul class="collapse">
  <li><a href="#iteration-with-a-single-input-function" id="toc-iteration-with-a-single-input-function" class="nav-link" data-scroll-target="#iteration-with-a-single-input-function"><span class="header-section-number">5.1</span> Iteration with a Single-Input Function</a></li>
  <li><a href="#iteration-with-a-double-input-function" id="toc-iteration-with-a-double-input-function" class="nav-link" data-scroll-target="#iteration-with-a-double-input-function"><span class="header-section-number">5.2</span> Iteration With a Double-Input Function</a></li>
  <li><a href="#iteration-with-a-multiple-input-function" id="toc-iteration-with-a-multiple-input-function" class="nav-link" data-scroll-target="#iteration-with-a-multiple-input-function"><span class="header-section-number">5.3</span> Iteration with a Multiple-Input Function</a></li>
  <li><a href="#writing-and-iteratively-applying-more-complex-functions" id="toc-writing-and-iteratively-applying-more-complex-functions" class="nav-link" data-scroll-target="#writing-and-iteratively-applying-more-complex-functions"><span class="header-section-number">5.4</span> Writing and Iteratively Applying More Complex Functions</a></li>
  </ul></li>
  <li><a href="#global-and-local-environments" id="toc-global-and-local-environments" class="nav-link" data-scroll-target="#global-and-local-environments"><span class="header-section-number">6</span> Global and Local Environments</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R Foundations: Basics of Functional Programming</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Aditya Ranganath </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>In this lesson, we’ll continue to develop an understanding of foundational skills and concepts that will allow you to use R effectively in applied social scientific research. Our goal is to develop an elementary proficiency in functional programming, which will allow you to fully exploit R’s capabilities when you use it for your research data tasks. A function is essentially a small program that takes an input (or series of inputs), run the input(s) through an algorithm, and produces output(s). Many functions come pre-programmed into R. R packages are essentially open-source user-written libraries of interrelated functions united by some theme, which we can draw on to extend the range of functions available to us. And finally, we can write our own custom-functions.</p>
<p>Given the enormous variety and sophistication of the R package ecosystem, you will not have to become an expert programmer to work with data in R; rather, you can draw on the functions others have written to implement virtually any data-related task you could imagine. However, developing a basic understanding of how to write your own functions is nevertheless important, for a variety of reasons:</p>
<ul>
<li>Sometimes, there won’t be a convenient pre-programmed function available to accomplish a given task, which will require you to write your own custom function.</li>
<li>Writing your own functions will allow you to automate your workflows</li>
<li>Writing functions will allow you to write more concise and readable code.</li>
</ul>
<p>With those considerations in mind, we’ll learn more about built-in functions in R and R packages, but our main purpose is to learn how to write some simple functions of our own. We’ll also learn more about how to use functions from the <em>purrr</em> package (part of the <em>tidyverse</em> suite) to iteratively apply our functions to multiple objects, which can help to automate common data processing tasks. In other words, iteration is the process of applying a function to each element in a vector, list, or data frame; it is a key part of functional programming that can save you enormous amounts of time and energy.</p>
</section>
<section id="built-in-functions" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Built-In Functions</h1>
<p>As we have noted, functions are programmatic constructs that take in a set of inputs, and return an output or set of outputs after applying an algorithm, or “recipe” to the set of inputs. The input(s) of a function are often called argument(s). Many functions come programmed into R. For example, there is the <code>sum()</code> function, which takes a numeric vector as an input, and returns the sum of those elements as an output. To see how this works, we’ll first create a toy numeric vector, <code>sample_vector</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creates a new numeric vector and assigns it to a new object named "sample_vector"</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sample_vector<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">11</span>, <span class="fl">5.6</span>, <span class="dv">8</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># prints contents of "sample_vector"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>sample_vector</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  5.0 11.0  5.6  8.0</code></pre>
</div>
</div>
<p>Now, we’ll pass <code>sample_vector</code> as an argument to the <code>sum()</code> function. The <code>sum()</code> function takes this argument, applies the algorithm to calculate the sum of vector elements that has been programmed into it, and returns the sum of the vector elements as the output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculates sum of vector elements using built-in "sum" function</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(sample_vector)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 29.6</code></pre>
</div>
</div>
<p>Another function is <code>prod(),</code> which returns the product of vector elements. Below, we pass <code>sample_vector</code> as an argument to this function, and it returns the product of the vector elements:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculates product of vector elements using built-in "prod" function</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(sample_vector)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2464</code></pre>
</div>
</div>
<p>Now, let’s use the built in <code>mean()</code> function to calculate the mean of the vector elements in <code>sample_vector</code>. We pass <code>sample_vector</code> as an argument to the <code>mean()</code> function, which performs the calculation based on its internal programming, and returns the mean of the vector elements as the output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculates the mean of vector elements</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(sample_vector)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.4</code></pre>
</div>
</div>
<p>Let’s try applying the <code>median()</code> function to <code>sample_vector</code> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculates the median of vector elements</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(sample_vector)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.8</code></pre>
</div>
</div>
<p>Thus far, we’ve been exploring elementary functions that perform mathematical calculations on numeric vectors. Let’s consider a function that’s relevant for character vectors. The <code>nchar()</code> function takes a string as an argument, and returns the number of characters in that string as the output. Below, we’ll pass the argument “Hello, World!” to <code>nchar(),</code> which returns the number of characters in that argument:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculates the number of characters in a string</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nchar</span>(<span class="st">"Hello, World!"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13</code></pre>
</div>
</div>
<p>Now, let’s consider the <code>colnames()</code> function, which is a built-in function that takes a data frame as an input, and returns the names of all of its columns. The argument to the <code>colnames()</code> function is <code>mtcars</code>, which is a dataset that’s built into R (R comes installed with several in-built datasets that are very helpful for practicing new skills and experimenting with code). If you’d like, you can get a sense of the <code>mtcars</code> dataset by passing it to the view function, or by viewing its documentation with <code>?mtcars</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extracts column names for "mtcars" dataset, which is built into R</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"</code></pre>
</div>
</div>
<p>We can also extract a data frame’s row names using the built-in <code>rownames()</code> function. Below, we’ll pass <code>mtcars</code> as an argument to <code>rownames()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">## extracts row names for "mtcars" dataset</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Mazda RX4"           "Mazda RX4 Wag"       "Datsun 710"         
 [4] "Hornet 4 Drive"      "Hornet Sportabout"   "Valiant"            
 [7] "Duster 360"          "Merc 240D"           "Merc 230"           
[10] "Merc 280"            "Merc 280C"           "Merc 450SE"         
[13] "Merc 450SL"          "Merc 450SLC"         "Cadillac Fleetwood" 
[16] "Lincoln Continental" "Chrysler Imperial"   "Fiat 128"           
[19] "Honda Civic"         "Toyota Corolla"      "Toyota Corona"      
[22] "Dodge Challenger"    "AMC Javelin"         "Camaro Z28"         
[25] "Pontiac Firebird"    "Fiat X1-9"           "Porsche 914-2"      
[28] "Lotus Europa"        "Ford Pantera L"      "Ferrari Dino"       
[31] "Maserati Bora"       "Volvo 142E"         </code></pre>
</div>
</div>
</section>
<section id="packages" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Packages</h1>
<p>R packages are essentially pre-written collections of functions organized around a given theme, and for most data processing and analysis tasks, one can rely on these pre-written functions embedded within packages (which we will do starting tomorrow). In some cases, however, you may want to write your own functions from scratch; it is also useful to have a basic sense of how functions work and are put together, so that you can use pre-written package-based functions more effectively.</p>
<section id="installing-packages" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="installing-packages"><span class="header-section-number">3.1</span> Installing Packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loading-libraries" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="loading-libraries"><span class="header-section-number">3.2</span> Loading Libraries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="writing-custom-functions" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Writing Custom Functions</h1>
<p>As we mentioned earlier, a function is a programming construct that takes a set of inputs (also known as arguments), manipulates those inputs/arguments in a specific way (the body of the function), and returns an output that is the product of how those inputs are manipulated in the body of the function. It is much like a recipe, where the recipe’s ingredients are analogous to a function’s inputs, the instructions about how to combine and process those ingredients are analogous to the body of the function, and the end product of the recipe (for example, a cake) is analogous to the function’s output.</p>
<p>In the previous section on built-in functions, we specified the functions’ arguments, and noted its outputs; the actual “recipes” were hidden from view. The best way to learn how these under-the-hood “recipes” work is to develop our own. To that end, we’ll now learn how to write some simple functions, and develop some intuition for how they are put together. Writing your own functions can be challenging, so we’ll develop our intuition by starting with a very simple example. In particular, we begin by writing a one-argument function; we then turn to writing a two-argument function; and then consider a multiple (more than two) input function.</p>
<section id="writing-one-input-functions" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="writing-one-input-functions"><span class="header-section-number">4.1</span> Writing One-Input Functions</h2>
<p>Let’s say we have a large collection of temperature data, measured in Fahrenheit, and we want to convert these data to Celsius. Recall that the formula to convert from Fahrenheit to Celsius is the following, where “C” represents temperature in Celsius, and “F” represents temperature in Fahrenheit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fahrenheit to Celsius formula, where C is Celsius output and F is Fahrenheit input</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>(F<span class="dv">-32</span>)<span class="sc">*</span>(<span class="dv">5</span><span class="sc">/</span><span class="dv">9</span>)<span class="ot">=</span>C</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As we discussed before, at its most basic level, R is a calculator; if for example, one of our Fahrenheit measurements is 55 degrees; we can convert this to Celsius by plugging 55 into the conversion formula:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Converts 55 degrees fahrenheit to Celsius</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>(<span class="dv">55-32</span>)<span class="sc">*</span>(<span class="dv">5</span><span class="sc">/</span><span class="dv">9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.77778</code></pre>
</div>
</div>
<p>This is easy enough, but if we have a large amount of temperature data that requires processing, we wouldn’t want to carry out this calculation for each measurement in our data collection. The first step in allowing us to carry out this conversion operation at scale is to write a function, which is simply a programming construct that takes a set of inputs (also known as arguments), manipulates those inputs/arguments in a specific way (the body of the function), and returns an output that is the product of how those inputs are manipulated in the body of the function. It is much like a recipe, where the recipe’s ingredients are analogous to a function’s inputs, the instructions about how to combine and process those ingredients are analogous to the body of the function, and the end product of the recipe (for example, a cake) is analogous to the function’s output.</p>
<p>Let’s see how we can wrap the Fahrenheit-Celsius formula above into a function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creates fahrenheit to celsius conversion function and assigns it to a new object named "fahrenheit_to_celsius_converter"</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>fahrenheit_to_celsius_converter<span class="ot">&lt;-</span><span class="cf">function</span>(fahrenheit_input){</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  celsius_output<span class="ot">&lt;-</span>(fahrenheit_input<span class="dv">-32</span>)<span class="sc">*</span><span class="dv">5</span><span class="sc">/</span><span class="dv">9</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(celsius_output)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s unpack the code above, which we used to create our function:</p>
<ul>
<li><p>We declare that we are creating a new function with the word&nbsp;<code>function</code>; within the parenthesis after&nbsp;<code>function</code>, we specify the function’s argument(s). Here, the function’s argument is an input named&nbsp;<code>fahrenheit_input</code>. The name of the argument(s) is arbitrary, and can be anything you like; ideally, its name should be informed by relevant context. Here, the argument/input to the function is a temperature value expressed in degrees Fahrenheit, so the name “fahrenheit_input” describes the nature of this input.</p></li>
<li><p>After enclosing the function’s arguments within parentheses, we print a right-facing curly brace&nbsp;<code>{</code>, and then define the body of the function (i.e.&nbsp;the recipe), which specifies how we want to transform this input. In particular, we take<code>fahrenheit_input</code>, subtract 32, and then multiply by 5/9, which transform the input to the celsius temperature scale. We’ll tell R to assign this transformed value to a new object, named&nbsp;<code>celsius_output</code>.</p></li>
<li><p>In the function’s final line,&nbsp;<code>return(celsius_output)</code>, we specify the value we want the function to return. Here, we are saying that we want the function to return the value that was assigned to&nbsp;<code>celsius_output</code>. We then close the function by typing a left-facing curly brace below the return statement&nbsp;<code>}</code>.</p></li>
<li><p>Just as we can assign data or visualizations to objects that allow us to subsequently retrieve the outputs of our code, so too with functions. Here, we’ll assign the function we have just return to an object named&nbsp;<code>fahrenheit_to_celsius_converter</code>.</p></li>
</ul>
<p>After running that code, we can use the newly created&nbsp;<code>fahrenheit_to_celsius</code>&nbsp;function to perform our Fahrenheit to Celsius transformations. Let’s say we have a Fahrenheit value of 68, and want to transform it to Celsius:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tests function using an input of 68 degrees fahrenheit</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fahrenheit_to_celsius_converter</span>(<span class="at">fahrenheit_input=</span><span class="dv">68</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20</code></pre>
</div>
</div>
<p>Above, we passed the argument <code>fahrenheit_input=68</code> to the&nbsp;<code>fahrenheit_to_celsius_converter()</code> function that we created; the function then took this value (68), plugged it into “fahrenheit_input” within the function and assigned the resulting value to “celsius_output”; it then returned the value of “celsius_output” (20) back to us. Note that while it’s good practice to label one’s arguments, as we did above (<code>fahrehnheit_input=68)</code>, it isn’t strictly necessary. For example, we could just enter a numeric argument for the temperature input, and the function will work:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># uses "fahrenheit_to_celsius_converter" function using an input of 20 degrees fahrenheit</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fahrenheit_to_celsius_converter</span>(<span class="dv">22</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -5.555556</code></pre>
</div>
</div>
<p>In short, we can specify any value for the “fahrenheit_input” argument; this value will be substituted for “fahrenheit_input” in the expression&nbsp;<code>celsius_output&lt;-(fahrenheit_input-32)*(5/9)</code>, after which the value of&nbsp;<code>celsius_output</code>&nbsp;will be returned to us.</p>
</section>
<section id="writing-two-input-functions" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="writing-two-input-functions"><span class="header-section-number">4.2</span> Writing Two-Input Functions</h2>
<p>Let’s extend what we learned above by writing a function that takes two arguments, rather than one. The principles are the same. To see this, let’s define a function that takes export and import values as arguments, and returns a value for net exports (defined as the difference between total exports and total imports). Below, we assign this function to an object named&nbsp;<code>net_exports_calculation()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># writes function that takes export and import values as inputs, and returns a value for net exports; function is assigned to a new object named "net_exports_calculation"</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>net_exports_calculation<span class="ot">&lt;-</span><span class="cf">function</span>(exports, imports){</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  net_export_value<span class="ot">&lt;-</span>exports<span class="sc">-</span>imports</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(net_export_value)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In essence, the function has two arguments, “exports” and “imports” that are supplied by the user; the body of the function takes these arguments, and subtracts the supplied value of imports from exports, and assigns this result to <code>net_export_value</code>, which it then returns as the output. Let’s go ahead and test the function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tests the "net_exports_calculation" function in a case where exports are 133, and imports are 55</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">net_exports_calculation</span>(<span class="at">exports=</span><span class="dv">133</span>, <span class="at">imports=</span><span class="dv">55</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 78</code></pre>
</div>
</div>
<p>The function works as expected. Note that if we switch the order in which we supply the arguments, the function continues to work as expected, so long as we label the arguments:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tests the "net_exports_calculation" function in a case where exports are 133, and imports are 55; reverses order in which inputs are supplied</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">net_exports_calculation</span>(<span class="at">imports=</span><span class="dv">55</span>, <span class="at">exports=</span><span class="dv">133</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 78</code></pre>
</div>
</div>
<p>However, if the arguments are not labelled, the order in which they are supplied does matter. That is, if the arguments are not labelled, the function assumes that they are passed in the order they’re defined in the function; in this case, that means that the assumption is that the first argument is the import argument and the second is the export argument. So, the following presumes that exports are 55, and imports are 133:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tests the "net_exports_calculation" function in a case where exports are 55, and imports are 133; does not explicitly label inputs, order matters</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">net_exports_calculation</span>(<span class="dv">55</span>, <span class="dv">133</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -78</code></pre>
</div>
</div>
<p>And the following presumes the opposite, that exports are 133, and imports are 55.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># uses the "net_exports_calculation" function in a case where exports are 133, and imports are 55; does not explicitly label inputs, order matters</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">net_exports_calculation</span>(<span class="dv">133</span>, <span class="dv">55</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 78</code></pre>
</div>
</div>
</section>
<section id="multiple-input-gdp-calculation-function" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="multiple-input-gdp-calculation-function"><span class="header-section-number">4.3</span> Multiple-Input GDP Calculation Function</h2>
<p>In this section, we’ll create a function that takes more than two inputs. In particular, we’ll create a function that takes numeric values for consumption spending (consumption_spending), government spending (government_spending), investment spending (investment_spending), and net exports (net_exports) as arguments, and returns a value for GDP (which is the sum of these values). We’ll assign this GDP calculator function to a new object named <code>gdp_calculation</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creates a new function that takes consumption spending, government spending, investment spending, and net exports as inputs, and returns a value for GDP by summing these elements; function is assigned to a new object named "gdp_calculation"</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>gdp_calculation<span class="ot">&lt;-</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(consumption_spending, government_spending, investment_spending, net_exports){</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  gdp<span class="ot">&lt;-</span>consumption_spending<span class="sc">+</span>government_spending<span class="sc">+</span>investment_spending<span class="sc">+</span>net_exports</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(gdp)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In short, the function takes values for consumption spending, government spending, investment spending, and net exports as user-supplied arguments; it then takes these values, adds them up, and assigns them to <code>gdp()</code>, which it returns as output.</p>
<p>Let’s now test the function; as before, we’ll assume that units are in millions of dollars. We’ll test our function for a country with consumption spending of $125 million (<code>consumption_spending=125</code>), government spending of $66 million (<code>government_spending=66</code>), investment spending of $36 million (<code>investment_spending=36</code>), and net exports of -$33 million (<code>net_exports=-33</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tests gdp calculation for consumption spending of 125, government spending of 66, investment spending of 36, and net exports of -33</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gdp_calculation</span>(<span class="at">consumption_spending =</span> <span class="dv">125</span>, <span class="at">government_spending=</span><span class="dv">66</span>, <span class="at">investment_spending=</span><span class="dv">36</span>, <span class="at">net_exports=</span><span class="sc">-</span><span class="dv">33</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 194</code></pre>
</div>
</div>
<p>As expected, the function returns the sum of these values, which translates into 194 (interpreted here as a GDP of $194 million).</p>
</section>
<section id="if-then-statements-in-functions" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="if-then-statements-in-functions"><span class="header-section-number">4.4</span> if-then Statements in Functions</h2>
<p>Now that we’re hopefully getting the hang of writing functions with any number of arguments, we can introduce a concept that will allow you to write more complex and sophisticated functions, namely conditional statements. By embedding conditional statements within functions, we enable them to make decisions based on whether a condition is true or false, and execute code accordingly. Conditional statements take the following form:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (condition1) {</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Code to execute if condition1 is TRUE</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> <span class="cf">if</span> (condition2) {</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Code to execute if condition1 is FALSE and condition2 is TRUE</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Code to execute if all the above conditions are FALSE</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>if</code> block is always evaluated first. If if the <code>if</code> condition is <code>FALSE</code>, the program moves to the <code>else if</code> block (there can be multiple such blocks). If none of the <code>if</code> or <code>else if</code> conditions are met, the <code>else</code> block (which is optional) executes.</p>
<p>Let’s take an example; below, we’ll create a function that takes two arguments, “value”, and “unit”. The “value” argument is a numeric temperature value, while “unit” is a string that specifies whether “value” is in Celsius or Fahrenheit. If the input temperature value is in Fahrenheit, the function coverts it to Celsius and returns this value; if the input value is not in Fahrenheit (i.e.&nbsp;is in Celsius), the function converts the input to Fahrenheit, and returns this value; and finally, if the specified input temperature is in neither Celsius nor Fahrenheit, the function returns a message saying “Please indicate whether your input is in Celsius or Fahrenheit”:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>convert_temperature <span class="ot">&lt;-</span> <span class="cf">function</span>(value, unit) {</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (unit <span class="sc">==</span> <span class="st">"Fahrenheit"</span>) {</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert Fahrenheit to Celsius</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    celsius <span class="ot">&lt;-</span> (value <span class="sc">-</span> <span class="dv">32</span>) <span class="sc">*</span> <span class="dv">5</span> <span class="sc">/</span> <span class="dv">9</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(celsius)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (unit <span class="sc">==</span> <span class="st">"Celsius"</span>) {</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert Celsius to Fahrenheit</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>    fahrenheit <span class="ot">&lt;-</span> (value <span class="sc">*</span> <span class="dv">9</span> <span class="sc">/</span> <span class="dv">5</span>) <span class="sc">+</span> <span class="dv">32</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(fahrenheit)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Handle invalid input for the unit</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="st">"Please indicate whether your input is in Celsius or Fahrenheit"</span>)</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s go ahead and test the function. Let’s say we want to convert 100 degrees Fahrenheit to Celsius:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Converts 100 degrees Fahrenheit to Celsius</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">convert_temperature</span>(<span class="dv">100</span>, <span class="st">"Fahrenheit"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37.77778</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Converts 25 degrees Celsius to Fahrenheit</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">convert_temperature</span>(<span class="dv">25</span>, <span class="st">"Celsius"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 77</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Attempts to convert 100 degrees Kelvin to another unit; met with a message specifying the function's constraints</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">convert_temperature</span>(<span class="dv">100</span>, <span class="st">"Kelvin"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Please indicate whether your input is in Celsius or Fahrenheit"</code></pre>
</div>
</div>
<p>As you can see, using if-then statements in a function allows functions to be flexible and dynamic, which can save time; instead of writing separate functions to convert Celsius to Fahrenheit and vice-versa, we can write a function that implements the conversion in either direction depending on the temperature value the user supplies.</p>
</section>
</section>
<section id="iteration" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Iteration</h1>
<p>Now that we have a sense of how to write basic functions, let’s now turn to the concept of iteration, which is fundamentally about applying a function across the elements of a vector, list, or data frame in a programmatic way. Functions and iteration are thus closely related; functions are programs that perform some action, while iteration applies those programs in a well-defined way so that those actions can be quickly and sequentially implemented across several objects. For example, we already have a function to convert Fahrenheit temperature values to Celsius temperature values; using this newly created function helps us to avoid manually converting each of our temperature values from the Fahrenheit scale to the Celsius scale; instead of repeating the calculation over and over manually, we could simply plug our Fahrenheit temperature values into the function, and let the function carry out the calculation for us. However, it is still time-consuming to plug our Fahrenheit values into the function one-by-one. Instead, we could deposit our Fahrenheit temperature values into a vector, and iteratively (i.e.&nbsp;sequentially) apply our function to all of these vector elements, and deposit the transformed results into a new vector (or a list, or as the rows of a data frame).</p>
<p>In programming languages, functions are typically applied to multiple inputs in an iterative fashion using a construct known as a for-loop, which some of you may already be familiar with. R users also frequently use specialized functions (instead of for-loops) to iterate over elements; this is often faster, or at the very least, makes R scripts more readable. One family of these iterative functions is the “Apply” family of functions. A more recent set of functions that facilitate iteration is part of the&nbsp;<em>tidyverse</em>, and is found within the <a href="#0">purrr</a> package. These functions known as <code>map()</code> functions, and we will use them in this lesson to iteratively apply our functions to multiple inputs.</p>
<p>There are many different kinds of <code>map()</code> functions within the <em>purrr</em> package, and we’ll introduce specific functions from this family of functions as we go. However, two of the fundamental map functions to be aware of at the outset are <code>map()</code>, which iterates over the elements of a vector or list, and deposits the results in a list, and <code>map_dbl(),</code> which iterates over the elements of a vector or list, and deposits the results in a numeric vector. If you’d like a preview of <code>map()</code> functions before we dive in, please consult the function’s documentation: <code>?map()</code>.</p>
<section id="iteration-with-a-single-input-function" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="iteration-with-a-single-input-function"><span class="header-section-number">5.1</span> Iteration with a Single-Input Function</h2>
<p>Let’s say we have four different Fahrenheit temperature values that we want to convert to Celsius: 45.6, 95.9, 67.8, 43. We could pass each input as an argument to <code>fahrenheit_to_celsius_converter()</code> individually, and get our Fahrenheit values that way, but it would quickly become tedious. Instead, we’ll implement a strategy that involves iteratively applying our function to those Fahrenheit temperature values. As a first step, we’ll create a vector of Fahrenheit temperature input arguments:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creates a vector of fahrenheit inputs</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>fahrenheit_input_vector<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fl">45.6</span>, <span class="fl">95.9</span>, <span class="fl">67.8</span>, <span class="dv">43</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we’ll use the <code>map()</code> function to iteratively apply <code>fahrenheit_to_celsius_converter()</code> to each element in that vector, and deposit the results in a list. We’ll pass<code>fahrenheit_input_vector</code>&nbsp;as the first argument to the&nbsp;<code>map()</code>&nbsp;function, and&nbsp;<code>fahrenheit_to_celsius_converter()</code>&nbsp;(i.e.&nbsp;the function we want to apply iteratively to the elements in `the<code>fahrenheit_input_vector</code>&nbsp;) as the second argument. The result of this operation will be a new “results list”, containing the transformed temperature values for each input in the original vector of Fahrenheit values (<code>fahrenheit_input_vector</code>). We’ll assign this result/output list to a new object named<code>celsius_outputs_list</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># iteratively applies the "fahrenheit_to_celsius_converter" function to the vector of inputs, "fahrenheit_input_vector", and assigns the resulting list of outputs to "celsius_outputs_vector"</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>celsius_outputs_list<span class="ot">&lt;-</span><span class="fu">map</span>(<span class="at">.x=</span>fahrenheit_input_vector, <span class="at">.f=</span>fahrenheit_to_celsius_converter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In short, the code above takes <code>fahrenheit_input_vector</code> and runs each of these numbers through the <code>fahrenheit_to_celsius_converter()</code> function, and sequentially deposits the transformed result to the newly created <code>celsius_outputs_list</code> object, which contains the transformed Celsius values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints contents of "celsius_outputs_list"</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>celsius_outputs_list</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 7.555556

[[2]]
[1] 35.5

[[3]]
[1] 19.88889

[[4]]
[1] 6.111111</code></pre>
</div>
</div>
<p>More explicitly, the code that reads&nbsp;<code>celsius_outputs_list&lt;-map(fahrenheit_input_vector, fahrenheit_converter)</code>did the following:</p>
<ol type="1">
<li><p>Pass 45.6 (the first element in the input vector,&nbsp;<code>fahrenheit_input_vector</code>) to the&nbsp;<code>fahrenheit_to_celsius_converter()</code>&nbsp;function, and place the output (7.555556) as the first element in a new list of transformed values, named&nbsp;<code>celsius_outputs_list</code>.</p></li>
<li><p>Pass 95.9 (the second element in the input vector,&nbsp;<code>fahrenheit_input_vector</code>) to the&nbsp;<code>fahrenheit_to_celsius_converter()</code>&nbsp;function, and deposit the output (35.500000) as the second element in&nbsp;<code>celsius_outputs_list</code>.</p></li>
<li><p>Pass 67.8 (the third element in the input vector,&nbsp;<code>fahrenheit_input_vector</code>) to the&nbsp;<code>fahrenheit_to_celsius_converter()</code>&nbsp;function, and deposit the output (19.888889) as the third element in&nbsp;<code>celsius_outputs_list</code>.</p></li>
<li><p>Pass 43 (the fourth element in the input vector,&nbsp;<code>fahrenheit_input_vector</code>) to the&nbsp;<code>fahrenheit_to_celsius_converter()</code>&nbsp;function, and deposit the output (6.111111) as the fourth element in&nbsp;<code>celsius_outputs_list</code>.</p></li>
</ol>
<p>Recall that if we want to extract an element from a list, we can do so by specifying its index within brackets. For instance, if we wanted to extract the second element in&nbsp;<code>celsius_outputs_list</code>, we could type the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extracts second element from "celsius_outputs_list"</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>celsius_outputs_list[[<span class="dv">2</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35.5</code></pre>
</div>
</div>
<p>As we have noted, there are a variety of <code>map()</code> functions, and the precise one you should use turns on the number of arguments used by the function (here, this value is of course one), and the desired class of the output (i.e.&nbsp;list, numeric vector etc.). Here, we used the core <code>map()</code> function because we wanted a list as an output, and we have a one-argument function that we are applying. Below, Below, we’ll talk more about how to handle functions with multiple arguments within the&nbsp;<em>purrr</em>&nbsp;ecosystem. Before that, though, let’s see how to use a slightly different type of <code>map()</code> function to return a different kind of output.</p>
<p>In particular, let’s say we want to iteratively apply the values in <code>fahrenheit_input_vector</code> as arguments arguments to the <code>fahrenheit_to_celsius_converter()</code> but that we want the outputs to be deposited in a numeric vector, rather than a list (as above). To do so, we can pass the same arguments we passed to the <code>map()</code> function, but use the <code>map_dbl()</code> function instead, which will output a vector:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># iteratively applies the "fahrenheit_to_celsius_converter" function to the vector of input arguments, "fahrenheit_input_vector", and assigns the resulting vector of outputs to "celsius_outputs_vector"</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>celsius_outputs_vector<span class="ot">&lt;-</span><span class="fu">map_dbl</span>(<span class="at">.x=</span>fahrenheit_input_vector, <span class="at">.f=</span>fahrenheit_to_celsius_converter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In short, the code above takes the first element of <code>fahrenheit_input_vector</code>, passes it as an input argument to <code>fahrenheit_to_celsius_converter()</code>, and deposits the output Celsius value as the first element in <code>celsius_outputs_vector</code>; it then takes the second element of <code>fahrenheit_input_vector</code>, passes it as an input argument to <code>fahrenheit_to_celsius_converter()</code>, and deposits the output Celsius value as the second element in <code>celsius_outputs_vector</code> ; and so on. Let’s print the contents of <code>celsius_outputs_vector</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints contents of "celsius_outputs_vector"</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>celsius_outputs_vector</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  7.555556 35.500000 19.888889  6.111111</code></pre>
</div>
</div>
<p>As expected, we see that it is a vector containing the output Fahrenheit values generated by the function.</p>
<p>What if we want a data frame that contains the input Fahrenheit values as one column, and the output Celsius columns as another? We can do so by using the <code>map_dbl()</code> function in conjunction with the arguments above within the <code>data.frame()</code> function that can define a data frame. In particular:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>fahrenheit_celsius_df_output<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">Fahrenheit=</span>fahrenheit_input_vector,</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">Celsius=</span><span class="fu">map_dbl</span>(<span class="at">.x=</span>fahrenheit_input_vector, <span class="at">.f=</span>fahrenheit_to_celsius_converter))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s confirm that the data frame has been created as expected:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints contents of "fahrenheit_celsius_df_output"</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>fahrenheit_celsius_df_output</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Fahrenheit   Celsius
1       45.6  7.555556
2       95.9 35.500000
3       67.8 19.888889
4       43.0  6.111111</code></pre>
</div>
</div>
<p>As you can see, we now have a handy data frame that has a column of Fahrenheit inputs, and a column of Celsius outputs.</p>
</section>
<section id="iteration-with-a-double-input-function" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="iteration-with-a-double-input-function"><span class="header-section-number">5.2</span> Iteration With a Double-Input Function</h2>
<p>In the previous subsection, we explored <code>map()</code> function in the context of working with single argument functions. In this section, we’ll explore how related functions from the <em>purrr</em> package can be used to iteratively pass arguments to a function with two input arguments. To illustrate, we will consider the <code>net_exports_calculation()</code> function we created above.</p>
<p>Let’s say we have export and import data from three countries, and want to calculate net exports for each country. First, we’ll deposit our input arguments into two different vectors. The numeric vector <code>export_vector</code> contains information for export values, while <code>import_vector</code> contains information on import values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creates export and import vectors</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>export_vector<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">78</span>, <span class="dv">499</span>, <span class="dv">785</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>import_vector<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">134</span>, <span class="dv">345</span>, <span class="dv">645</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we’ll use the <code>map2()</code> function to iteratively pass through the input arguments from these two vectors to the <code>net_exports_calculation()</code> function, and deposit the outputs (i.e.&nbsp;net export values) into a list, which we’ll assign to an object named <code>net_export_list</code>. The “.x” label signifies that <code>export_vector</code> provides information on the first argument to the <code>net_exports_calculation()</code> function, while the “.y” label signifies that <code>import_vector</code> provides information on the second argument to <code>net_exports_calculation()</code>. The “.f” label signifies the name of the function to which we’re applying these arguments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># iteratively applies the "net_exports_calculation" function to the export values contained in "export_vector" and the import values contained in "import_vector" and deposits the resulting outputs in a list that's assigned to the new object entitled "net_export_list"</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>net_export_list<span class="ot">&lt;-</span><span class="fu">map2</span>(<span class="at">.x=</span>export_vector, <span class="at">.y=</span>import_vector, <span class="at">.f=</span>net_exports_calculation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In short, the code above takes the first value in <code>export_vector</code> and the first value in <code>import_vector</code> and passes these values to <code>net_exports_calculation</code> to calculate net exports for the first country, which is then deposited as the first element in <code>net_export_list</code>; then, it takes the second value in <code>export_vector</code> and the second value in <code>import_vector</code> and passes these values to <code>net_exports_calculation</code> to calculate net exports for the second country, which is then deposited as the second element in <code>net_export_list;</code> and likewise for the third country. We can print the contents of <code>net_export_list</code> to ensure that the code worked as expected:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints contents of "net_export_list"</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>net_export_list</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] -56

[[2]]
[1] 154

[[3]]
[1] 140</code></pre>
</div>
</div>
<p>If, instead of depositing the results into a list, we’d like to deposit our outputs into a numeric vector, we can do so using the<code>map2_dbl()</code>&nbsp;function, the analog of&nbsp;<code>map_dbl()</code>&nbsp;which is used when the function takes two inputs rather than one. We’ll assign our results vector to a new object named&nbsp;<code>net_export_vector</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># iteratively applies the "net_exports_calculation" function to the export values contained in "export_vector" and the import values contained in "import_vector" and deposits the resulting outputs in a vector that's assigned to the new object entitled "net_export_vector"</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>net_export_vector<span class="ot">&lt;-</span><span class="fu">map2_dbl</span>(<span class="at">.x=</span>export_vector, <span class="at">.y=</span>import_vector, <span class="at">.f=</span>net_exports_calculation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s print the contents of <code>net_export_vector</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints contents of "net_export_vector"</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>net_export_vector</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -56 154 140</code></pre>
</div>
</div>
<p>If, instead, we’d like a data frame that contains exports in the first column, imports in the second column, and net exports in the third, we could use the <code>data.frame()</code> function, and run the code that generated <code>net_export_vector</code> within it. We’ll assign this data frame to a new object named <code>net_exports_dataframe</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creates data frame with exports in first column, imports in second column, and net exports in third; assigns the data frame to a new object named "net_exports_dataframe"</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>net_exports_dataframe<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">exports=</span>export_vector,</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">imports=</span>import_vector,</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">net_exports=</span><span class="fu">map2_dbl</span>(<span class="at">.x=</span>export_vector, <span class="at">.y=</span>import_vector, <span class="at">.f=</span>net_exports_calculation))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Of course, we could have also created the data frame above with the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative way of creating "net_exports_dataframe"</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">exports=</span>export_vector,</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">imports=</span>import_vector,</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">net_exports=</span>net_export_vector)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  exports imports net_exports
1      78     134         -56
2     499     345         154
3     785     645         140</code></pre>
</div>
</div>
</section>
<section id="iteration-with-a-multiple-input-function" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="iteration-with-a-multiple-input-function"><span class="header-section-number">5.3</span> Iteration with a Multiple-Input Function</h2>
<p>While the&nbsp;<code>map2()</code>&nbsp;family functions allows us to conveniently handle iteration tasks involving two-argument functions, we will often need to write and work with functions with more than two argument. How can we carry out iteration tasks when we need to iteratively apply multiple input arguments to a function?</p>
<p>The&nbsp;<code>pmap()</code>&nbsp;family of functions within&nbsp;<em>purrr</em>&nbsp;allows us to handle iteration tasks using functions with any number of inputs greater than two, by using a list as a container for all of the input arguments we would like to iteratively pass to a functions. To see how this works, let’s consider the <code>gdp_calculator()</code> function that we created above. Let’s say we have consumption spending, government spending, investment spending, and net export data for four different countries, and we want to iteratively apply the data for these countries as arguments to <code>gdp_calculator()</code> and derive the GDP for each country.</p>
<p>The first step is to create a new list of input arguments, where each list element is a vector that contains the country-level values for each argument of the&nbsp;<code>gdp_calculation()</code>&nbsp;function. We’ll assign this list to a new object named&nbsp;<code>gdp_input_list</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creates a list as a container for the input arguments we'll iteratively run through the "gdp_calculation" function</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>gdp_input_list<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">consumption_spending=</span><span class="fu">c</span>(<span class="dv">44</span>, <span class="dv">89</span>, <span class="dv">64</span>, <span class="dv">33</span>),</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">government_spending=</span><span class="fu">c</span>(<span class="dv">54</span>, <span class="dv">76</span>, <span class="dv">222</span>, <span class="dv">110</span>),</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">investment_spending=</span><span class="fu">c</span>(<span class="dv">123</span>, <span class="dv">200</span>, <span class="dv">55</span>, <span class="dv">45</span>),</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">net_exports=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">55</span>, <span class="dv">89</span>, <span class="dv">143</span>,<span class="sc">-</span><span class="dv">12</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To make sure we understand what&nbsp;<code>gdp_input_list</code>&nbsp;represents, consider the first element in each of the four numeric vectors in the list; these first elements correspond to the first country, which we can see has consumption spending of $44, government spending of $54, investment spending of $123, and net exports of -$55. The second element of each of the vectors in the list corresponds to information for the second country, which has consumption spending of $89, government spending of $76, investment spending of $200, and net exports of $89. And so on for Countries 3 and 4.</p>
<p>Now that we have defined our list of input values (<code>gdp_input_list</code>) based on the arguments to the&nbsp;<code>gdp_calculation()</code> function, we can pass&nbsp;<code>gdp_input_list</code> (the list of input values) and&nbsp;<code>gdp_calculation()</code> (the function to which we’re iteratively passing the arguments in <code>gdp_input_list</code>) as arguments to&nbsp;<em>purrr’s</em>&nbsp;<code>pmap()</code>&nbsp;function. The <code>pmap()</code> function iteratively passes the arguments in the input list to the <code>gdp_calculation()</code> function in a vectorized fashion. That is, the <code>pmap()</code> function uses the first element in each vector of the input list to generate the first output value, then uses the second element in each vector of the input list to generate the second output value, and so on. We’ll assign the resulting list of output values to a new object named <code>gdp_output_list</code>. The “.l” label is used to designate the list of input arguments, while the “.f” argument designates the function to which we are iteratively passing arguments from the input list:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># iteratively passes arguments from "gdp_input_list" to the "gdp_calculation" function and deposits the results in a new list object named "gdp_output_list"</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>gdp_output_list<span class="ot">&lt;-</span><span class="fu">pmap</span>(<span class="at">.l=</span>gdp_input_list, <span class="at">.f=</span>gdp_calculation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s now print the contents of&nbsp;<code>gdp_output_list</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints contents of "gdp_output_list"</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>gdp_output_list</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 166

[[2]]
[1] 454

[[3]]
[1] 484

[[4]]
[1] 176</code></pre>
</div>
</div>
<p>As expected, the first list element contains the GDP of the first country, 166 (44+54+123+55); the second list element contains the GDP of the second country, 454 (89+76+200+89); and so on, for the third and fourth countries.</p>
<p>If, instead, we want the results deposited in a vector, we can use the <code>pmap_dbl()</code> function instead:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># iteratively passes arguments from "gdp_input_list" to the "gdp_calculation" function and deposits the results in a new list object named "gdp_output_vector"</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>gdp_output_vector<span class="ot">&lt;-</span><span class="fu">pmap_dbl</span>(<span class="at">.l=</span>gdp_input_list, <span class="at">.f=</span>gdp_calculation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s print the contents of <code>gdp_output_vector</code> and confirm that it contains the expected outputs of the GDP function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints contents of "gdp_output_vector"</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>gdp_output_vector</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 166 454 484 176</code></pre>
</div>
</div>
<p>As an exercise below, we’ll ask you to assemble a data frame in which consumption spending, government spending, investment spending, and net exports for these countries are in columns, along with another column that contains the GDP value.</p>
</section>
<section id="writing-and-iteratively-applying-more-complex-functions" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="writing-and-iteratively-applying-more-complex-functions"><span class="header-section-number">5.4</span> Writing and Iteratively Applying More Complex Functions</h2>
<p>Now, let’s see how we can iteratively apply a more complex function with multiple inputs, and which makes use of “if-then” statements that result in different outputs depending on whether certain conditions are met. We’ll slightly modify the <code>convert_temperature()</code> function we created above. In particular, this function will take three inputs; the first specifies the name of a country, the second specifies a temperature in either Celsius or Fahrenheit, and the third provides information on whether the temperature value is provided in Celsius or Fahrenheit.</p>
<p>If the temperature is provided in Fahrenheit, the function converts this value to Celsius, while also recording the temperature in Fahrenheit based on the input value. If the temperature is provided in Celsius, it converts Celsius to Fahrenheit, while also recording the temperature in Celsius based on the input value. Then, it uses this information to create a one-row data frame, where the columns are the Country, temperature in Celsius, and temperature in Fahrenheit. The function below is extensively commented; see if you can make sense of its logic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creates new function to take a country name, temperature value in either Celsius or Fahrenheit, and a designation for the temperature unit as inputs, and return a data frame with the country name, temperature value in Fahrenheit, and Temperature value in Celsius as columns; the function is assigned to a new object named "convert_temperature_df"</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>convert_temperature_df <span class="ot">&lt;-</span> <span class="cf">function</span>(country, temperature, unit) {</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Check if the unit is valid</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (unit <span class="sc">==</span> <span class="st">"Fahrenheit"</span>) {</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert Fahrenheit to Celsius</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>    celsius <span class="ot">&lt;-</span> (temperature <span class="sc">-</span> <span class="dv">32</span>) <span class="sc">*</span> <span class="dv">5</span> <span class="sc">/</span> <span class="dv">9</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>    fahrenheit <span class="ot">&lt;-</span> temperature</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (unit <span class="sc">==</span> <span class="st">"Celsius"</span>) {</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert Celsius to Fahrenheit</span></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>    fahrenheit <span class="ot">&lt;-</span> (temperature <span class="sc">*</span> <span class="dv">9</span> <span class="sc">/</span> <span class="dv">5</span>) <span class="sc">+</span> <span class="dv">32</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>    celsius <span class="ot">&lt;-</span> temperature</span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Throw an error if the unit is invalid</span></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">"Error: Please indicate whether your input is in 'Celsius' or 'Fahrenheit'"</span>)</span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create and return a data frame</span></span>
<span id="cb76-18"><a href="#cb76-18" aria-hidden="true" tabindex="-1"></a>  result <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb76-19"><a href="#cb76-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">Country =</span> country,</span>
<span id="cb76-20"><a href="#cb76-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">Temperature_Celsius =</span> <span class="fu">round</span>(celsius, <span class="dv">2</span>),   <span class="co"># Round to 2 decimal places</span></span>
<span id="cb76-21"><a href="#cb76-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">Temperature_Fahrenheit =</span> <span class="fu">round</span>(fahrenheit, <span class="dv">2</span>)</span>
<span id="cb76-22"><a href="#cb76-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb76-23"><a href="#cb76-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb76-24"><a href="#cb76-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(result)</span>
<span id="cb76-25"><a href="#cb76-25" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, let’s go ahead and test this function, where the country is “USA”, and the temperature in Fahrenheit is 100:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tests "convert_temperature_df" function for USA as the country input, and a temperature of 100 degrees in Fahrenheit</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">convert_temperature_df</span>(<span class="st">"USA"</span>, <span class="dv">100</span>, <span class="st">"Fahrenheit"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Country Temperature_Celsius Temperature_Fahrenheit
1     USA               37.78                    100</code></pre>
</div>
</div>
<p>As we can see, the function behaved as expected; it creates a data frame where the country is “USA”, and there are columns for the temperature in Celsius and Fahrenheit. In this case, the Fahrenheit temperature was filled in by the user-supplied argument, while the Celsius temperature was filled in by transforming the Fahrenheit temperature value to the Celsius scale within the function.</p>
<p>Let’s test the function again, with different input arguments:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tests "convert_temperature_df" function for India as the country input, and a temperature of 100 degrees in Fahrenheit</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">convert_temperature_df</span>(<span class="st">"India"</span>, <span class="dv">39</span>, <span class="st">"Celsius"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Country Temperature_Celsius Temperature_Fahrenheit
1   India                  39                  102.2</code></pre>
</div>
</div>
<p>Again, the function behaves as expected. It creates a data frame where the country is “India”, and columns for the temperature in Celsius and Fahrenheit. In this case, the Celsius temperature was filled in by the user-supplied argument, while the Fahrenheit temperature was filled in by transforming the Celsius temperature value to the Fahrenheit scale within the function.</p>
<p>Now, let’s imagine we have data for several countries, and we want to iteratively pass this data as arguments to <code>convert_temperature_df</code> to generate a data frame with information on the temperatures for these countries. To do so, we can use the <code>pmap()</code> function. First, we’ll create a list with vectors that contain the input arguments we want to pass to the function; we’ll assign this list to a new object named <code>input_list_temperatures</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creates a list of inputs to iterate over</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>input_list_temperatures<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">country=</span><span class="fu">c</span>(<span class="st">"USA"</span>, <span class="st">"Canada"</span>, <span class="st">"Mexico"</span>, <span class="st">"France"</span>),</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">temperature=</span><span class="fu">c</span>(<span class="dv">66</span>, <span class="dv">11</span>, <span class="dv">25</span>, <span class="dv">33</span>),</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">unit=</span><span class="fu">c</span>(<span class="st">"Fahrenheit"</span>, <span class="st">"Celsius"</span>, <span class="st">"Fahrenheit"</span>, <span class="st">"Celsius"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we’ll pass this list and the <code>convert_temperature_df()</code> function as arguments to <code>pmap()</code>, and assign the resulting list of outputs to a new object named <code>convert_temperature_list</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># iteratively applies the "convert_temperature_df" function using the input variables in "input_list_temperatures"; the outputs are deposited in a list assigned to the object named "convert_temperature_list"</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>convert_temperature_list<span class="ot">&lt;-</span><span class="fu">pmap</span>(<span class="at">.l=</span>input_list_temperatures, <span class="at">.f=</span>convert_temperature_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code above first takes the first elements in the vectors in <code>input_list_temperatures</code> (“USA, 66,”Fahrenheit”), runs them through the <code>convert_temperature_df()</code> function, and deposits the resulting data frame as the first element in <code>convert_temperature_list</code>. It then takes the second elements in the vectors in <code>input_list_temperatures</code> (“Canada”, 11, “Celsius”), passes them as arguments to the <code>convert_temperature_df()</code> function, and deposits the resulting data frame as the second element in <code>convert_temperature_list.</code> And so on.</p>
<p>Let’s now print the contents of <code>convert_temperature_list</code> , which should contain four single-row data frames:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints contents of "convert_temperature_list"</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>convert_temperature_list</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
  Country Temperature_Celsius Temperature_Fahrenheit
1     USA               18.89                     66

[[2]]
  Country Temperature_Celsius Temperature_Fahrenheit
1  Canada                  11                   51.8

[[3]]
  Country Temperature_Celsius Temperature_Fahrenheit
1  Mexico               -3.89                     25

[[4]]
  Country Temperature_Celsius Temperature_Fahrenheit
1  France                  33                   91.4</code></pre>
</div>
</div>
<p>As we can see, the data frames are stored separately as list elements (which is what we expected). If we’d like to bind these data frame rows together into a single, consolidated data frame, we can easily do so by passing <code>convert_temperature_list</code> as an argument to the <code>bind_rows()</code> function. We’ll assign this data frame to a new object named <code>convert_temperature_df_final</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># appends together the single-row data frames in "convert_temperature_list" into a single data frame by passing "convert_temperature_list" as an argument to "bind_rows"; the newly created data frame is assigned to a new object named "convert_temperature_df_final"</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>convert_temperature_df_final<span class="ot">&lt;-</span><span class="fu">bind_rows</span>(convert_temperature_list)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints contents of "convert_temperature_df_final"</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>convert_temperature_df_final</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Country Temperature_Celsius Temperature_Fahrenheit
1     USA               18.89                   66.0
2  Canada               11.00                   51.8
3  Mexico               -3.89                   25.0
4  France               33.00                   91.4</code></pre>
</div>
</div>
<p>Finally, it’s worth noting that it’s possible to incorporate iteration processes with <code>map()</code> family functions within our custom-written functions. In other words, we can include <code>map()</code> functions within the body of our functions, rather than simply using them after we’ve created functions. Moreover, its possible to incorporate functions we’ve already written into new custom functions; incorporating “functions within functions” can often help us accomplish some very useful tasks.</p>
<p>Let’s consider an example, by writing a new function that takes takes a vector of Fahrenheit temperature values and transforms these values to the Celsius scale. It will return these transformed values either as a list, vector, or data frame containing the initial Fahrenheit temperatures as one column, and the transformed Celsius temperatures in another, depending on the user’s preference (which is the second argument to the function.</p>
<p>Below, the function’s first argument is the vector of Fahrenheit temperatures, while the second is the user’s preference over whether the transformed values are returned as a list (“List), vector (”Vector”), or data frame (“Data.Frame”). If the user desires the output as a list, the function passes the vector of Fahrenheit inputs as an argument to the <code>map()</code> function, along with the <code>fahrenheit_to_celsius_converter()</code> that we defined earlier. This will iteratively pass the temperature values in the input vector as arguments to <code>fahrenheit_to_celsius_converter,</code> and the output Celsius temperatures are deposited in a list (given the behavior of the <code>map()</code> function). If, instead, the user desires the output as a numeric vector, the function passes the the vector of Fahrenheit inputs as an argument to the <code>map_dbl()</code> function, along with the <code>fahrenheit_to_celsius_converter().</code> This will iteratively pass the temperature values in the input vector as arguments to <code>fahrenheit_to_celsius_converter,</code> and the output Celsius temperatures are deposited in a vector (given the behavior of the <code>map_dbl()</code> function). Finally, if the user desires a data frame, the function will create a data frame using the <code>data.frame()</code> function, and define a column for Fahrenheit values using the vector of inputs, and a column of Celsius temperature values using the vector of transformed Celsius values created by <code>map_dbl(.x=vector_of_fahrenheit_inputs, .f =fahrenheit_to_celsius_converter)</code>. We’ll assign this function to a new object named <code>fahrenheit_to_celsius_general()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Writes a function that takes a vector of fahrenheit temperature values, and returns either a list, data frame, or vector of outputs depending on the user's desired output; assigns the function to a new object named "fahrenheit_to_celsius_general"</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>fahrenheit_to_celsius_general<span class="ot">&lt;-</span><span class="cf">function</span>(vector_of_fahrenheit_inputs, desired_output){</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>   <span class="cf">if</span> (desired_output <span class="sc">==</span> <span class="st">"List"</span>) {</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>     outputlist<span class="ot">&lt;-</span><span class="fu">map</span>(<span class="at">.x=</span>vector_of_fahrenheit_inputs, <span class="at">.f=</span>fahrenheit_to_celsius_converter)</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>     <span class="fu">return</span>(outputlist)</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>   } <span class="cf">else</span> <span class="cf">if</span> (desired_output<span class="sc">==</span><span class="st">"Vector"</span>){</span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>     outputvector<span class="ot">&lt;-</span><span class="fu">map_dbl</span>(<span class="at">.x=</span>vector_of_fahrenheit_inputs, <span class="at">.f =</span>fahrenheit_to_celsius_converter)</span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>     <span class="fu">return</span>(outputvector)</span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>   } <span class="cf">else</span> <span class="cf">if</span> (desired_output<span class="sc">==</span><span class="st">"Data.Frame"</span>){</span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a>     outputdf<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">Fahrenheit=</span>vector_of_fahrenheit_inputs,</span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a>                          <span class="at">Celsius=</span><span class="fu">map_dbl</span>(<span class="at">.x=</span>vector_of_fahrenheit_inputs, <span class="at">.f =</span>fahrenheit_to_celsius_converter))</span>
<span id="cb88-12"><a href="#cb88-12" aria-hidden="true" tabindex="-1"></a>     <span class="fu">return</span>(outputdf)</span>
<span id="cb88-13"><a href="#cb88-13" aria-hidden="true" tabindex="-1"></a>   } <span class="cf">else</span> {</span>
<span id="cb88-14"><a href="#cb88-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">stop</span>(<span class="st">"Error: Please indicate whether your desired output is a 'Vector', 'Data.Frame', or 'List'"</span>)</span>
<span id="cb88-15"><a href="#cb88-15" aria-hidden="true" tabindex="-1"></a>   }</span>
<span id="cb88-16"><a href="#cb88-16" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, let’s test this function out. First, we’ll define a vector of Fahrenheit values we’d like to convert, and assign it to a new object named <code>test_vector_ftoc</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tests "fahrenheit_to_celsius_general" function; first, defines a vector of fahrenheit values</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>test_vector_ftoc<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">66</span>, <span class="dv">88</span>, <span class="sc">-</span><span class="dv">12</span>, <span class="dv">7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s test the function by passing <code>test_vector_ftoc</code> as an argument, along with specifying “Data.Frame” as our desired output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># uses "fahrenheit_to_celsius_general" function to convert the temperature values in "test_vector_ftoc" to Celsius and return a data frame with input Fahrenheit values in one column, and corresponding celsius temperatures in another column</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fahrenheit_to_celsius_general</span>(<span class="at">vector_of_fahrenheit_inputs=</span>test_vector_ftoc, <span class="at">desired_output=</span><span class="st">"Data.Frame"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Fahrenheit    Celsius
1         18  -7.777778
2         66  18.888889
3         88  31.111111
4        -12 -24.444444
5          7 -13.888889</code></pre>
</div>
</div>
<p>The function behaves as expected. Now, let’s try specifying that we want the transformed Celsius temperatures as a list:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># uses "fahrenheit_to_celsius_general" function to convert the temperature values in "test_vector_ftoc" to Celsius and return the outputs as a list</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fahrenheit_to_celsius_general</span>(<span class="at">vector_of_fahrenheit_inputs=</span>test_vector_ftoc, <span class="at">desired_output=</span><span class="st">"List"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] -7.777778

[[2]]
[1] 18.88889

[[3]]
[1] 31.11111

[[4]]
[1] -24.44444

[[5]]
[1] -13.88889</code></pre>
</div>
</div>
<p>Finally, we’ll check the function’s behavior when we request the output as a vector:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># uses "fahrenheit_to_celsius_general" function to convert the temperature values in "test_vector_ftoc" to Celsius and return the outputs as a vector</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fahrenheit_to_celsius_general</span>(<span class="at">vector_of_fahrenheit_inputs=</span>test_vector_ftoc, <span class="at">desired_output=</span><span class="st">"Vector"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  -7.777778  18.888889  31.111111 -24.444444 -13.888889</code></pre>
</div>
</div>
<p>It’s worth noting that when we request an output that is not supported, we receive the expected error message. For example, let’s specify our desired output as a tibble (i.e.&nbsp;a special type of data frame):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># uses "fahrenheit_to_celsius_general" function to convert the temperature values in "test_vector_ftoc" to Celsius and return the outputs as a vector</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fahrenheit_to_celsius_general</span>(<span class="at">vector_of_fahrenheit_inputs=</span>test_vector_ftoc, <span class="at">desired_output=</span><span class="st">"Tibble"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in fahrenheit_to_celsius_general(vector_of_fahrenheit_inputs = test_vector_ftoc, : Error: Please indicate whether your desired output is a 'Vector', 'Data.Frame', or 'List'</code></pre>
</div>
</div>
</section>
</section>
<section id="global-and-local-environments" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Global and Local Environments</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define a variable in the global environment</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="dv">24</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>toy_function<span class="ot">&lt;-</span><span class="cf">function</span>(input1){</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  x<span class="ot">&lt;-</span><span class="dv">5</span></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  z<span class="ot">&lt;-</span>x<span class="sc">+</span>input1</span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(z)</span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">toy_function</span>(<span class="at">input1=</span><span class="dv">7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints value of x</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints value of z</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>z</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error: object 'z' not found</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints objects</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "celsius_outputs_list"            "celsius_outputs_vector"         
 [3] "convert_temperature"             "convert_temperature_df"         
 [5] "convert_temperature_df_final"    "convert_temperature_list"       
 [7] "export_vector"                   "fahrenheit_celsius_df_output"   
 [9] "fahrenheit_input_vector"         "fahrenheit_to_celsius_converter"
[11] "fahrenheit_to_celsius_general"   "gdp_calculation"                
[13] "gdp_input_list"                  "gdp_output_list"                
[15] "gdp_output_vector"               "import_vector"                  
[17] "input_list_temperatures"         "net_export_list"                
[19] "net_export_vector"               "net_exports_calculation"        
[21] "net_exports_dataframe"           "sample_vector"                  
[23] "test_vector_ftoc"                "toy_function"                   
[25] "x"                              </code></pre>
</div>
</div>
<p>Key points:</p>
<ul>
<li><p>The global object <code>x</code> remains unchanged at 24, despite the fact that it’s assigned the value 5 within <code>toy_function()</code></p></li>
<li><p>The local object <code>x</code> only exists while the function runs</p></li>
<li><p><code>Z</code> is created in the function’s local environment and disappears after the function finishes running</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>